kind: pipeline
type: docker
name: x86_64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: abyssos/abyss:latest
  commands:
  - /bin/sh ./build.sh

- name: push
  image: abyssos/abyss:latest
  commands:
  - apk add minio-client
  - /bin/sh ./upload.sh
  environment:
    MC_HOST_master:
      from_secret: MC_HOST_master
  when:
    branch:
    - master

---
kind: pipeline
type: docker
name: aarch64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: abyssos/abyss:latest
  commands:
  - /bin/sh ./build.sh

- name: push
  image: abyssos/abyss:latest
  commands:
  - apk add minio-client
  - /bin/sh ./upload.sh
  environment:
    MC_HOST_master:
      from_secret: MC_HOST_master
  when:
    branch:
    - master

