kind: pipeline
name: default

steps:
- name: build image
  image: abyssos/abyss
  commands:
  - /bin/sh ./build.sh

- name: deploy image
  image: minio/mc
  commands:
  - /bin/sh ./upload.sh mc
  environment:
    s3_id:
      from_secret: s3_id
    s3_key:
      from_secret: s3_key
    s3_endpoint:
      from_secret: s3_endpoint
    MC_HOST_master:
      from_secret: MC_HOST_master
  when:
    branch:
    - master
