kind: pipeline
name: default

steps:
- name: build image
  image: abyssos/abyss
  commands:
  - /bin/sh ./build.sh

- name: deploy image
  image: plugins/s3
  settings:
    path_style: true
    source: "abyss.tar.gz"
    target: "/lxd"
    bucket:
      from_secret: s3_id
    access_key:
      from_secret: s3_id
    secret_key:
      from_secret: s3_key
    endpoint:
      from_secret: s3_endpoint
  when:
    branch:
    - master
